#!/bin/sh

eval "$(dbus-launch --sh-syntax --exit-with-session)"

xwallpaper --stretch ~/Pictures/wallpapers/$(ls ~/Pictures/wallpapers | shuf -n 1) &
setxkbmap -option caps:swapescape &
redshift &
xcompmgr &
xset r rate 300 50 &
dunst &
slstatus &
exec dbus-launch --sh-syntax --exit-with-session dwm
