#!/bin/sh

xwallpaper --stretch ~/Pictures/wallpapers/$(ls ~/Pictures/wallpapers | shuf -n 1)  &
setxkbmap -option caps:swapescape &
mpd &
redshift &
xcompmgr &
xset r rate 300 50 &
dunst &
slstatus &
#xautolock -time 2 -locker slock &
exec dbus-launch --sh-syntax --exit-with-session dwm
