#!/bin/sh

xwallpaper --stretch ~/Pictures/wallpapers/$(ls ~/Pictures/wallpapers | shuf)  &
setxkbmap -option caps:swapescape &
redshift &
xcompmgr &
xset r rate 300 50 &
dunst &
slstatus &
exec dbus-launch --sh-syntax --exit-with-session dwm
